version: '3.3'

services:
  db:
    image: mysql:8.0
    restart: always
    container_name: blog
    environment:
      MYSQL_DATABASE: 'blog'
      MYSQL_ROOT_PASSWORD: 'p@ssword'
    ports:
      - '3337:3306'
    volumes:
      - ./data:/var/lib/mysql
  test_db:
    image: mysql:8.0
    restart: always
    container_name: blog_test
    environment:
      MYSQL_DATABASE: 'blog-test'
      MYSQL_ROOT_PASSWORD: 'p@ssword'
    ports:
      - '3338:3306'
    volumes:
      - ./test_data:/var/lib/mysql
