version: '3.3'

services:
  blog-ringo-service:
    build: .
    image: blog-ringo
    container_name: blog-ringo-service
    ports:
      - '8080:8080'
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    container_name: blog
    environment:
      MYSQL_DATABASE: 'blog'
      MYSQL_ROOT_PASSWORD: 'p@ssword'
    ports:
      - '3337:3306'
    volumes:
      - ./data:/var/lib/mysql

