authorization:
  jwt:
    secret: BlogSecretKeyToGenJWTs
    expires: 1800000

server:
  port: 8080

spring:
  swagger:
    enabled: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: <<Flyway Baseline>>
    url: jdbc:mysql://localhost:3337/blog?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_bin&useServerPrepStmts=false&rewriteBatchedStatements=true&createDatabaseIfNotExist=true
    user: root
    password: p@ssword
  datasource:
    url: jdbc:mysql://localhost:3337/blog?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_bin&useServerPrepStmts=false&rewriteBatchedStatements=true&createDatabaseIfNotExist=true
    username: root
    password: p@ssword
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate



